language: ruby
cache: bundler
rvm:
  - 2.7
  - 3.0
  - 3.1
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build deliverr_api.gemspec
  - gem install ./deliverr_api-1.0.0.gem
