=begin
#Deliverr API

# **Note:** As of February 24 2023, Deliverr is not accepting new API accounts. Existing integrations already using the Deliverr API in production may continue usage and development.  All other Deliverr accounts initiating Deliverr API requests will be denied access. A new Logistics API is being developed by Shopify and will be replacing the Deliverr API.  # Getting Started  To start using the Deliverr API, you must have an active login account to the Deliverr web portal. To inbound physical inventory, ship orders, process returns or parcel transactions, you'll also need to set up a billing account.  ## If you do not already have a Deliverr account 1. Create an account for free at https://sellerportal.deliverr.com 2. When you are asked to choose an integration, you can click <b>Skip</b> at the upper right corner 3. Once you have logged in, you can start the OAuth process below  ## If you already have a Deliverr account 1. You can access the Products, Webhooks and Reports API immediately regardless of billing status 2. All other APIs available will require you to have set up billing with Deliverr 3. The Returns, Parcel, and Parcel Integration APIs are only accessible to select merchants  ## Guides and examples  Please visit the <a href='https://support.deliverr.com/hc/en-us/sections/6332705638423-Deliverr-API'>Deliverr API Guide</a> to view steps and code examples.  # Release Notes  Please refer to the following <a href='https://support.deliverr.com/hc/en-us/articles/9399822031383'>Deliverr API - Release Notes</a> help center article to view the most recent changes to Deliverr API.  # Status Page  You can find information about the current status of the API endpoints at <a href='https://deliverrstatus.com/'>deliverrstatus.com</a>  

The version of the OpenAPI document: 1.0.0
Contact: support@deliverr.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DeliverrAPI::BundlesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BundlesApi' do
  before do
    # run before each test
    @api_instance = DeliverrAPI::BundlesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BundlesApi' do
    it 'should create an instance of BundlesApi' do
      expect(@api_instance).to be_instance_of(DeliverrAPI::BundlesApi)
    end
  end

  # unit tests for create_bundle
  # Creates a new bundle.
  # @param api_bundle_model 
  # @param [Hash] opts the optional parameters
  # @return [ApiBundleModelResponse]
  describe 'create_bundle test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_bundle
  # Get bundle information for a bundle.
  # @param bundle_id 
  # @param [Hash] opts the optional parameters
  # @return [ApiBundleModelResponse]
  describe 'get_bundle test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_bundle_by_external_bundle_id
  # Get bundle information for a bundle by the external bundle id assigned.
  # @param external_bundle_id 
  # @param [Hash] opts the optional parameters
  # @return [ApiBundleModelResponse]
  describe 'get_bundle_by_external_bundle_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_bundle_inventory
  # Get available inventory information for the bundle.
  # @param bundle_id 
  # @param [Hash] opts the optional parameters
  # @return [ApiBundleInventoryResponseModel]
  describe 'get_bundle_inventory test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for link_alias_to_bundle
  # Links an externalBundleId to an existing bundle. A bundle can only be linked to one externalBundleId.
  # @param bundle_id 
  # @param external_bundle_id 
  # @param [Hash] opts the optional parameters
  # @return [ApiBundleModelResponse]
  describe 'link_alias_to_bundle test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for unlink_alias_from_bundles
  # Unlinks an externalBundleId from any existing bundle it is currently associated with.
  # @param external_bundle_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'unlink_alias_from_bundles test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
