=begin
#Deliverr API

# **Note:** As of February 24 2023, Deliverr is not accepting new API accounts. Existing integrations already using the Deliverr API in production may continue usage and development.  All other Deliverr accounts initiating Deliverr API requests will be denied access. A new Logistics API is being developed by Shopify and will be replacing the Deliverr API.  # Getting Started  To start using the Deliverr API, you must have an active login account to the Deliverr web portal. To inbound physical inventory, ship orders, process returns or parcel transactions, you'll also need to set up a billing account.  ## If you do not already have a Deliverr account 1. Create an account for free at https://sellerportal.deliverr.com 2. When you are asked to choose an integration, you can click <b>Skip</b> at the upper right corner 3. Once you have logged in, you can start the OAuth process below  ## If you already have a Deliverr account 1. You can access the Products, Webhooks and Reports API immediately regardless of billing status 2. All other APIs available will require you to have set up billing with Deliverr 3. The Returns, Parcel, and Parcel Integration APIs are only accessible to select merchants  ## Guides and examples  Please visit the <a href='https://support.deliverr.com/hc/en-us/sections/6332705638423-Deliverr-API'>Deliverr API Guide</a> to view steps and code examples.  # Release Notes  Please refer to the following <a href='https://support.deliverr.com/hc/en-us/articles/9399822031383'>Deliverr API - Release Notes</a> help center article to view the most recent changes to Deliverr API.  # Status Page  You can find information about the current status of the API endpoints at <a href='https://deliverrstatus.com/'>deliverrstatus.com</a>  

The version of the OpenAPI document: 1.0.0
Contact: support@deliverr.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DeliverrAPI::OrdersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrdersApi' do
  before do
    # run before each test
    @api_instance = DeliverrAPI::OrdersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrdersApi' do
    it 'should create an instance of OrdersApi' do
      expect(@api_instance).to be_instance_of(DeliverrAPI::OrdersApi)
    end
  end

  # unit tests for cancel_order
  # Cancel an order that was created via the \&quot;Create Order\&quot; endpoint. If an order has already been processed and shipped, the order cannot be cancelled.
  # @param order_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :x_deliverr_mock_request if this header is set to \&quot;true\&quot; the request will be treated as a mock request.
  # @return [nil]
  describe 'cancel_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_order
  # Create an order to be fulfilled. &lt;P&gt;&lt;B&gt;Shipment and Delivery SLAs&lt;/B&gt; All orders are assigned a shipping date based on when they were originally placed. All orders are assigned a shipping SLA for expected shipment time and delivery time after being imported. To meet buyer expectations it&#39;s vital that this reflects customer expectations when the order is placed.&lt;P&gt; The logic of evaluating the provided field is:&lt;P&gt; &lt;OL&gt; &lt;LI&gt;If the &lt;B&gt;orderDeliveryTime&lt;/B&gt; field is present and valid, the value will be set as the SLA time &lt;LI&gt;Otherwise, if the &lt;B&gt;deliveryDays&lt;/B&gt; value is set and valid, that number of days will be added onto the calculated shipment date to determine the delivery date.&lt;/LI&gt; &lt;LI&gt;Otherwise if the &lt;B&gt;shipMethod&lt;/B&gt; is present, it will be mapped to a calculated delivery speed, if unrecognized or invalid, the shipping delivery date will be set to 5 days after the shipment date&lt;/LI&gt; &lt;/OL&gt;
  # @param order_api_create_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @option opts [Boolean] :x_deliverr_mock_request if this header is set to \&quot;true\&quot; the request will be treated as a mock request. Note that if the shipMethod field is passed in for a mock order, it will be translated to a orderDeliveryTime of 2 days from now.
  # @return [OrderApiStatusModel]
  describe 'create_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_order
  # Get order information for an order created via the \&quot;Create order\&quot; endpoint. If the order has been shipped, the response will contain shipping information.
  # @param order_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :x_deliverr_mock_request if this header is set to \&quot;true\&quot; the request will be treated as a mock request.
  # @return [OrderApiStatusModel]
  describe 'get_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_order_by_external_id
  # Get order information for an order created via the \&quot;Create order\&quot; endpoint, using the external order ID given during order creation. If the order has been shipped, the response will contain shipping information.
  # @param external_order_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :x_deliverr_mock_request if this header is set to \&quot;true\&quot; the request will be treated as a mock request.
  # @return [OrderApiStatusModel]
  describe 'get_order_by_external_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retry_order
  # Retries processing of a fulfillment order.
  # @param order_id 
  # @param [Hash] opts the optional parameters
  # @return [OrderApiStatusModel]
  describe 'retry_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
