=begin
#Deliverr API

# **Note:** As of February 24 2023, Deliverr is not accepting new API accounts. Existing integrations already using the Deliverr API in production may continue usage and development.  All other Deliverr accounts initiating Deliverr API requests will be denied access. A new Logistics API is being developed by Shopify and will be replacing the Deliverr API.  # Getting Started  To start using the Deliverr API, you must have an active login account to the Deliverr web portal. To inbound physical inventory, ship orders, process returns or parcel transactions, you'll also need to set up a billing account.  ## If you do not already have a Deliverr account 1. Create an account for free at https://sellerportal.deliverr.com 2. When you are asked to choose an integration, you can click <b>Skip</b> at the upper right corner 3. Once you have logged in, you can start the OAuth process below  ## If you already have a Deliverr account 1. You can access the Products, Webhooks and Reports API immediately regardless of billing status 2. All other APIs available will require you to have set up billing with Deliverr 3. The Returns, Parcel, and Parcel Integration APIs are only accessible to select merchants  ## Guides and examples  Please visit the <a href='https://support.deliverr.com/hc/en-us/sections/6332705638423-Deliverr-API'>Deliverr API Guide</a> to view steps and code examples.  # Release Notes  Please refer to the following <a href='https://support.deliverr.com/hc/en-us/articles/9399822031383'>Deliverr API - Release Notes</a> help center article to view the most recent changes to Deliverr API.  # Status Page  You can find information about the current status of the API endpoints at <a href='https://deliverrstatus.com/'>deliverrstatus.com</a>  

The version of the OpenAPI document: 1.0.0
Contact: support@deliverr.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DeliverrAPI::ProductsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProductsApi' do
  before do
    # run before each test
    @api_instance = DeliverrAPI::ProductsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductsApi' do
    it 'should create an instance of ProductsApi' do
      expect(@api_instance).to be_instance_of(DeliverrAPI::ProductsApi)
    end
  end

  # unit tests for create_product
  # Create a new product.
  # @param api_product_model 
  # @param [Hash] opts the optional parameters
  # @return [ApiProductModelResponse]
  describe 'create_product test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_product_barcode
  # Validates and assigns a new barcode to this product.
  # @param product_id 
  # @param barcode_option 
  # @param [Hash] opts the optional parameters
  # @return [ApiProductModelResponse]
  describe 'create_product_barcode test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all_inventory
  # Get all inventory.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [Integer] :offset 
  # @option opts [InventoryPool] :pool_name 
  # @return [Array<ApiInventoryResponseModel>]
  describe 'get_all_inventory test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_product
  # Get product information for products.
  # @param product_id 
  # @param [Hash] opts the optional parameters
  # @return [ApiProductModelResponse]
  describe 'get_product test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_product_by_external_product_id
  # Get product information for products.
  # @param external_product_id 
  # @param [Hash] opts the optional parameters
  # @return [ApiProductModelResponse]
  describe 'get_product_by_external_product_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_product_inventory
  # Get available inventory information for product.
  # @param product_id 
  # @param [Hash] opts the optional parameters
  # @option opts [InventoryPool] :pool_name 
  # @return [ApiInventoryResponseModel]
  describe 'get_product_inventory test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_products
  # Get a list of products and their information.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [Integer] :offset 
  # @return [Array<ApiProductModelResponse>]
  describe 'get_products test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_warehouse_details
  # Get warehouse information for a given list of productIds.
  # @param product_ids 
  # @param [Hash] opts the optional parameters
  # @option opts [InventoryPool] :pool_name 
  # @return [Array<ApiWarehouseResponseModel>]
  describe 'get_warehouse_details test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for link_alias_to_product
  # Links an externalProductId to an existing product. A product can only be linked to one externalProductId.
  # @param product_id 
  # @param external_product_id 
  # @param [Hash] opts the optional parameters
  # @return [ApiProductModelResponse]
  describe 'link_alias_to_product test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for unlink_alias_from_products
  # Unlinks an externalProductId from any existing product it is currently associated with.
  # @param external_product_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'unlink_alias_from_products test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_product
  # Update product attributes.
  # @param product_id 
  # @param api_update_product_model 
  # @param [Hash] opts the optional parameters
  # @return [ApiProductModelResponse]
  describe 'update_product test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
