=begin
#Deliverr API

# **Note:** As of February 24 2023, Deliverr is not accepting new API accounts. Existing integrations already using the Deliverr API in production may continue usage and development.  All other Deliverr accounts initiating Deliverr API requests will be denied access. A new Logistics API is being developed by Shopify and will be replacing the Deliverr API.  # Getting Started  To start using the Deliverr API, you must have an active login account to the Deliverr web portal. To inbound physical inventory, ship orders, process returns or parcel transactions, you'll also need to set up a billing account.  ## If you do not already have a Deliverr account 1. Create an account for free at https://sellerportal.deliverr.com 2. When you are asked to choose an integration, you can click <b>Skip</b> at the upper right corner 3. Once you have logged in, you can start the OAuth process below  ## If you already have a Deliverr account 1. You can access the Products, Webhooks and Reports API immediately regardless of billing status 2. All other APIs available will require you to have set up billing with Deliverr 3. The Returns, Parcel, and Parcel Integration APIs are only accessible to select merchants  ## Guides and examples  Please visit the <a href='https://support.deliverr.com/hc/en-us/sections/6332705638423-Deliverr-API'>Deliverr API Guide</a> to view steps and code examples.  # Release Notes  Please refer to the following <a href='https://support.deliverr.com/hc/en-us/articles/9399822031383'>Deliverr API - Release Notes</a> help center article to view the most recent changes to Deliverr API.  # Status Page  You can find information about the current status of the API endpoints at <a href='https://deliverrstatus.com/'>deliverrstatus.com</a>  

The version of the OpenAPI document: 1.0.0
Contact: support@deliverr.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'date'
require 'time'

module DeliverrAPI
  class ParcelTrackingGetResponse
    # Unique ID used to track the parcel, returned after acquiring a purchase label.
    attr_accessor :parcel_id

    # The customer reference id.
    attr_accessor :customer_reference_id

    # An optional field to input additional information about the parcel.
    attr_accessor :customer_custom_field

    # Status of the tracking request.
    attr_accessor :status

    # Errors associated with the response.
    attr_accessor :errors

    # Error messages associated with the response.
    attr_accessor :error_message

    # URL that can be used to track the package.
    attr_accessor :package_tracking_url

    # URL used to download the label data.
    attr_accessor :shipping_label_url

    # The tracking code for the package.
    attr_accessor :tracking_code

    # The carrier code for the package.
    attr_accessor :carrier_code

    attr_accessor :event_timestamps

    attr_accessor :expired_tracking_data

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'parcel_id' => :'parcelId',
        :'customer_reference_id' => :'customerReferenceId',
        :'customer_custom_field' => :'customerCustomField',
        :'status' => :'status',
        :'errors' => :'errors',
        :'error_message' => :'errorMessage',
        :'package_tracking_url' => :'packageTrackingUrl',
        :'shipping_label_url' => :'shippingLabelUrl',
        :'tracking_code' => :'trackingCode',
        :'carrier_code' => :'carrierCode',
        :'event_timestamps' => :'eventTimestamps',
        :'expired_tracking_data' => :'expiredTrackingData'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'parcel_id' => :'String',
        :'customer_reference_id' => :'String',
        :'customer_custom_field' => :'String',
        :'status' => :'String',
        :'errors' => :'String',
        :'error_message' => :'String',
        :'package_tracking_url' => :'String',
        :'shipping_label_url' => :'String',
        :'tracking_code' => :'String',
        :'carrier_code' => :'String',
        :'event_timestamps' => :'TrackingResultTimestamps',
        :'expired_tracking_data' => :'Array<ExpiredTrackingData>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DeliverrAPI::ParcelTrackingGetResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DeliverrAPI::ParcelTrackingGetResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'parcel_id')
        self.parcel_id = attributes[:'parcel_id']
      end

      if attributes.key?(:'customer_reference_id')
        self.customer_reference_id = attributes[:'customer_reference_id']
      end

      if attributes.key?(:'customer_custom_field')
        self.customer_custom_field = attributes[:'customer_custom_field']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'errors')
        self.errors = attributes[:'errors']
      end

      if attributes.key?(:'error_message')
        self.error_message = attributes[:'error_message']
      end

      if attributes.key?(:'package_tracking_url')
        self.package_tracking_url = attributes[:'package_tracking_url']
      end

      if attributes.key?(:'shipping_label_url')
        self.shipping_label_url = attributes[:'shipping_label_url']
      end

      if attributes.key?(:'tracking_code')
        self.tracking_code = attributes[:'tracking_code']
      end

      if attributes.key?(:'carrier_code')
        self.carrier_code = attributes[:'carrier_code']
      end

      if attributes.key?(:'event_timestamps')
        self.event_timestamps = attributes[:'event_timestamps']
      end

      if attributes.key?(:'expired_tracking_data')
        if (value = attributes[:'expired_tracking_data']).is_a?(Array)
          self.expired_tracking_data = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @event_timestamps.nil?
        invalid_properties.push('invalid value for "event_timestamps", event_timestamps cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @status.nil?
      return false if @event_timestamps.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          parcel_id == o.parcel_id &&
          customer_reference_id == o.customer_reference_id &&
          customer_custom_field == o.customer_custom_field &&
          status == o.status &&
          errors == o.errors &&
          error_message == o.error_message &&
          package_tracking_url == o.package_tracking_url &&
          shipping_label_url == o.shipping_label_url &&
          tracking_code == o.tracking_code &&
          carrier_code == o.carrier_code &&
          event_timestamps == o.event_timestamps &&
          expired_tracking_data == o.expired_tracking_data
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [parcel_id, customer_reference_id, customer_custom_field, status, errors, error_message, package_tracking_url, shipping_label_url, tracking_code, carrier_code, event_timestamps, expired_tracking_data].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = DeliverrAPI.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
