=begin
#Deliverr API

# **Note:** As of February 24 2023, Deliverr is not accepting new API accounts. Existing integrations already using the Deliverr API in production may continue usage and development.  All other Deliverr accounts initiating Deliverr API requests will be denied access. A new Logistics API is being developed by Shopify and will be replacing the Deliverr API.  # Getting Started  To start using the Deliverr API, you must have an active login account to the Deliverr web portal. To inbound physical inventory, ship orders, process returns or parcel transactions, you'll also need to set up a billing account.  ## If you do not already have a Deliverr account 1. Create an account for free at https://sellerportal.deliverr.com 2. When you are asked to choose an integration, you can click <b>Skip</b> at the upper right corner 3. Once you have logged in, you can start the OAuth process below  ## If you already have a Deliverr account 1. You can access the Products, Webhooks and Reports API immediately regardless of billing status 2. All other APIs available will require you to have set up billing with Deliverr 3. The Returns, Parcel, and Parcel Integration APIs are only accessible to select merchants  ## Guides and examples  Please visit the <a href='https://support.deliverr.com/hc/en-us/sections/6332705638423-Deliverr-API'>Deliverr API Guide</a> to view steps and code examples.  # Release Notes  Please refer to the following <a href='https://support.deliverr.com/hc/en-us/articles/9399822031383'>Deliverr API - Release Notes</a> help center article to view the most recent changes to Deliverr API.  # Status Page  You can find information about the current status of the API endpoints at <a href='https://deliverrstatus.com/'>deliverrstatus.com</a>  

The version of the OpenAPI document: 1.0.0
Contact: support@deliverr.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'date'
require 'time'

module DeliverrAPI
  class ReturnStatus
    CREATED = "CREATED".freeze
    BUYER_SHIPPED = "BUYER_SHIPPED".freeze
    SHIPPED = "SHIPPED".freeze
    BUYER_DELIVERED = "BUYER_DELIVERED".freeze
    QC_RECEIVED = "QC_RECEIVED".freeze
    QC_PROCESSED = "QC_PROCESSED".freeze
    QC_SHIPPED = "QC_SHIPPED".freeze
    CANCELLED = "CANCELLED".freeze
    COMPLETED = "COMPLETED".freeze
    RETURNED_TO_SENDER = "RETURNED_TO_SENDER".freeze
    REQUESTED = "REQUESTED".freeze
    RECEIVED_FOR_PROCESSING = "RECEIVED_FOR_PROCESSING".freeze
    PROCESSED = "PROCESSED".freeze
    AUTO_CANCELLED = "AUTO_CANCELLED".freeze
    REJECTED = "REJECTED".freeze
    RECEIVED_AT_DROPPOINT = "RECEIVED_AT_DROPPOINT".freeze

    def self.all_vars
      @all_vars ||= [CREATED, BUYER_SHIPPED, SHIPPED, BUYER_DELIVERED, QC_RECEIVED, QC_PROCESSED, QC_SHIPPED, CANCELLED, COMPLETED, RETURNED_TO_SENDER, REQUESTED, RECEIVED_FOR_PROCESSING, PROCESSED, AUTO_CANCELLED, REJECTED, RECEIVED_AT_DROPPOINT].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ReturnStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ReturnStatus"
    end
  end
end
